dependencies {
    implementation project(":edison-aws-core")
    implementation libs.aws.sdk.core
    implementation libs.spring.boot.autoconfigure
    implementation libs.spring.boot.starter.actuator
    implementation libs.hibernate.validator
    implementation libs.aws.sdk.cloudwatch
    implementation libs.micrometer
    implementation libs.micrometer.cloudwatch
    implementation libs.guava
    implementation libs.apache.commons

    testImplementation libs.junit.jupiter
    testImplementation libs.hamcrest.core
    testImplementation libs.mockito.core
}

artifacts {
    archives jar
    archives javadocJar
    archives sourcesJar
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = 'edison-aws-metrics'
            from components.java
            artifact sourcesJar
            artifact javadocJar
            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }
            pom {
                name = 'edison-aws-metrics'
                description = 'CloudWatch metrics reporter library of the edison-aws project.'
                url = 'http://github.com/otto-de/edison-aws'
                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }
                developers {
                    developer {
                        id = 'gsteinacker'
                        name = 'Guido Steinacker'
                    }
                }
                scm {
                    connection = 'scm:git@github.com:otto-de/edison-aws.git'
                    developerConnection = 'scm:git@github.com:otto-de/edison-aws.git'
                    url = 'https://github.com/otto-de/edison-aws'
                }
            }
        }
    }
}

