apply plugin: 'java-library'

dependencies {
    api platform(libs.edison.platform)

    implementation libs.spring.boot.autoconfigure
    implementation libs.aws.sdk.core
    implementation libs.aws.sdk.auth
    implementation libs.slf4j
}

artifacts {
    archives jar
    archives javadocJar
    archives sourcesJar
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = 'edison-aws-core'
            from components.java
            artifact sourcesJar
            artifact javadocJar
            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }
            pom {
                name = 'edison-aws-core'
                description = 'Core library of Edison-AWS microservices.'
                url = 'http://github.com/otto-de/edison-aws'
                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }
                developers {
                    developer {
                        id = 'gsteinacker'
                        name = 'Guido Steinacker'
                    }
                }
                scm {
                    connection = 'scm:git@github.com:otto-de/edison-aws.git'
                    developerConnection = 'scm:git@github.com:otto-de/edison-aws.git'
                    url = 'https://github.com/otto-de/edison-aws'
                }
            }
        }
    }
}

