dependencies {
    implementation project(":edison-aws-core")
    implementation project(":edison-aws-s3")

    implementation libs.spring.boot.autoconfigure
    implementation libs.aws.sdk.ssm
    implementation libs.aws.sdk.s3  // without_log4j wird nicht mehr benötigt
    implementation libs.slf4j

    testImplementation libs.junit.jupiter
    testImplementation libs.mockito.core
    testImplementation libs.hamcrest.core
    testImplementation libs.spring.boot.starter.test
}

artifacts {
    archives jar
    archives javadocJar
    archives sourcesJar
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = 'edison-aws-config'
            from components.java
            artifact sourcesJar
            artifact javadocJar
            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }
            pom {
                name = 'edison-aws-config'
                description = 'Configuration of Edison-AWS microservices.'
                url = 'http://github.com/otto-de/edison-aws'
                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }
                developers {
                    developer {
                        id = 'gsteinacker'
                        name = 'Guido Steinacker'
                    }
                }
                scm {
                    connection = 'scm:git@github.com:otto-de/edison-aws.git'
                    developerConnection = 'scm:git@github.com:otto-de/edison-aws.git'
                    url = 'https://github.com/otto-de/edison-aws'
                }
            }
        }
    }
}

