dependencies {
    implementation project(":edison-aws-core")

    implementation libs.spring.boot.autoconfigure
    implementation libs.aws.sdk.s3
    implementation libs.slf4j
    implementation libs.jackson
    implementation libs.jackson.databind
    implementation libs.jackson.annotations

    implementation libs.java.validation.api

    compileOnly libs.edison.togglz

    testImplementation libs.edison.togglz

    testImplementation libs.spring.boot.starter.test
    testImplementation libs.junit.jupiter
    testImplementation libs.mockito.core
    testImplementation libs.hamcrest.core
    testImplementation libs.togglz.testing
}

artifacts {
    archives jar
    archives javadocJar
    archives sourcesJar
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = 'edison-aws-s3'
            from components.java
            artifact sourcesJar
            artifact javadocJar
            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }
            pom {
                name = 'edison-aws-core'
                description = 'Basic support for S3 in Edison-AWS microservices.'
                url = 'http://github.com/otto-de/edison-aws'
                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }
                developers {
                    developer {
                        id = 'gsteinacker'
                        name = 'Guido Steinacker'
                    }
                }
                scm {
                    connection = 'scm:git@github.com:otto-de/edison-aws.git'
                    developerConnection = 'scm:git@github.com:otto-de/edison-aws.git'
                    url = 'http://github.com/otto-de/edison-aws'
                }
            }
        }
    }
}

signing {
    sign publishing.publications.mavenJava
}
